### ISSUE TITLE
survey_sd with vartype and level

### ISSUE THREAD

**Issue by nalimilan** [gergness/srvyr#112]
Is there any reason why `survey_sd` doesn't allow passing `vartype` and `level`? I imagine passing these arguments to `survey_var` should be OK mathematically?

**Comment by gergness** [comment]
Finally got around to looking into this, it's because the survey package doesn't estimate a `sd`, it just provides the variance, which we calculate using the squareroot. I don't think you could use the squareroot in the same way for other measures.

**Comment by gergness** [comment]
I suppose level could easily be allowed

**Comment by nalimilan** [comment]
But if we can get the confidence interval for the variance, then by definition the CI for the standard deviation can be obtained by taking the square root of the lower and upper bound, right?

**Comment by gergness** [comment]
I don't think that's necessarily true and I don't feel qualified to adjudicate. If you need this, I think you should just calculate the squareroot yourself.

I can imagine places where this breaks down, eg here the variance's CI is less than 0, so squareroot would lead to an imaginary CI.

``` r
library(srvyr)

example <- as_survey(
  data.frame(id = 1:4, x = c(1, 1, 1, 2))
) %>%
  summarize(var = survey_var(x, vartype = "ci")) 

example
#>    var    var_low   var_upp
#> 1 0.25 -0.2804077 0.7804077

example %>%
  mutate(across(.fns = sqrt))
#> Warning: Problem with `mutate()` input `..1`.
#> ℹ NaNs produced
#> ℹ Input `..1` is `across(.fns = sqrt)`.
#> Warning in fn(col, ...): NaNs produced
#>   var var_low   var_upp
#> 1 0.5     NaN 0.8834069
```

<sup>Created on 2021-01-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by nalimilan** [comment]
Oh interesting. I would say that since a negative variance doesn't make any sense, the negative lower bound is just due to the way the interval is constructed. There's a similar issue with `confint(svymean(...))`, [which `svycipro` avoids](https://r-survey.r-forge.r-project.org/survey/html/svyciprop.html). At any rate, IMHO returning `NaN` for the lower bound would be fine in that case, actually it's less misleading than the negative bounds for variance. :-)

(I know I can compute the CI myself. I filed this issue only because I felt embarrassed when trying to explain to my students that there was no direct way to compute CIs for standard deviation -- which sounds like a trivial operation.)

**Comment by gergness** [comment]
Looking back at the PR that introduced this function, @tzoltak seemed to have a strong handle on the statistics (which I definitely do not). @tzoltak, any chance you're still around? Can you weigh in on whether `survey_sd` can get `vartype` and level arguments? 

https://github.com/gergness/srvyr/pull/48#discussion_r270235195

Looks like you originally had a lot of misgivings about CIs for even `survey_var`, but ultimately decided that it was worth it. Did you deliberately leave off `survey_sd` or was it more just that you didn't get around to it after you changed your mind?

**Comment by tzoltak** [comment]
Taking the root square of the lower and upper bound of CI for variance to get bounds of CI for SD is on the one hand something easy, but that's something completely different than the way _srvyr_ computes CIs for the other statistics, so it calls for implementing some custom workaround that would make internal structure of the package a little tricky. I suppose that's the reason I avoided this. I see no other reasons not to implement CIs for SD.

Regarding negative values of the lower bound of CI for variance, the way CIs are estimated relies on asymptotic assumption that the sampling distribution of variance approaches normal distribution (or perhaps t - I would need to look at _srvyr_ or perhaps _survey_ internals_ to check, that's not crucial however). If this assumption doesn't hold, bounds of CI can be severely biased and lower bound may be negative quite frequently. Dealing with the substitution by `NaN`s is just another special case to be handled within _srvyr_ - @gergness needs to tell how he feels about it. Moreover _srvyr_ generally relies on _survey_ regrading computation of SEs and CIs, so I think it would be better to ask Thomas Lumley so he makes something like `svycipro` for variance - than it can be used within _srvyr_ :)

In case of SE for SD things are a little more complicated, because I would need to spent some time reading, how this should be implemented - linearization must be employed to do this.

**Comment by tzoltak** [comment]
I thought about it a little and simple linear approximation for SE of SD is: `(0.5*Var^-0.5)*SE(Var)` (i.e. multiplying by derivative of a square root at the value of variance). Nevertheless there's still decision to be made whether implementing a custom workaround for calculating SD's SE and CI in the package.

**Comment by nalimilan** [comment]
Thanks @tzoltak. I think we could write to Thomas Lumley, I've done that in the past about various issues in survey and he's been quite responsive. @gergness Let me know if you're interested.

**Comment by gergness** [comment]
Yeah, sounds good. In an ideal world, Professor Lumley would implement a `svysd` in the survey package with these calculations that srvyr could use. I like to keep as much of the calculations there so that I don't have to feel responsible for them.
