### ISSUE TITLE
should srvyr just pass through arguments by default?

### ISSUE THREAD

**Issue by ajdamico** [gergness/srvyr#14]
hi, impressive work

two examples of parameters that srvyr currently cannot handle..

	library(srvyr)
	library(survey)
	data(api)

	dclus1<- apiclus1 %>% as_survey_design(id=dnum, weights=pw, fpc=fpc)

	# possible to pass through design effect parameter?
	svytotal( ~ stype , dclus1 , deff = TRUE )

	# works
	confint(svymean(~api00, dclus1))
	dclus1 %>% summarise(api00 = survey_mean(api00, vartype = "ci"))

	# possible to pass through degrees of freedom parameter?
	confint(svymean(~api00, dclus1), df=degf(dclus1))
	dclus1 %>% summarise(api00 = survey_mean(api00, vartype = "ci",df=degf(dclus1)))

you pull the design object out of the the `args` parameter [here](https://github.com/gergness/srvyr/blob/master/R/survey_statistics.r#L151) and then basically discard it.  at the point you pull out `.svy` you could then 
    
    args[".svy"]<- NULL

and then you have an `args` parameter that can be passed through to the subsequent functions.

ultimately, when you get to [running the actual function](https://github.com/gergness/srvyr/blob/master/R/survey_statistics.r#L478) from the `survey` package, you could change

    stat <- func(data.frame(x), .svy, na.rm = na.rm)

to

    stat <- do.call( func , c( list( data.frame(x) , .svy , na.rm = na.rm ) , args ) )

and it will run the `func` with all of the user-supplied arguments?  i think?

this would allow you to not worry about parameters like `na.rm=` and `f=` and other less commonly-used parameters but still maintain the flexibility that lumley has created..

**Comment by gergness** [comment]
Hey thanks! Yeah, I never got around to these, I'll take a look over the weekend.

Do any of your examples use these parameters? I'd be interested in seeing a normal use case. (I've wondered if they should be set at either the design level, or once per `summarize()` call, but can imagine reasons why it is structured the way it is in the survey package).

**Comment by ajdamico** [comment]
hmmm, sometimes it would be nice to set globally and other times it'd be better to set it on every line, so i am not sure.  here are some examples using `degf()`  https://github.com/ajdamico/asdfree/search?utf8=%E2%9C%93&q=degf but there's lots more in that repo

**Comment by gergness** [comment]
I think I have to continue implementing arguments piecemeal because srvyr doesn't have a 1 to 1 correspondence with survey functions. (eg `df` must be passed to `survey::confint.svystat()`, but `na.rm`, `deff`, etc. are passed to `survey::svymean()`). I don't mind this, because it makes sure I document all arguments.

I've added `deff=` and `df=` to survey_mean and survey_total so far. Are there other arguments I should add?   ( @ajdamico , You wrote "parameters like `na.rm=` and `f=`", is that "f=" a typo for "df="?). I'll work on survey_ratio and quantile/median next.

Also, is there any reason not to use the degrees of freedom from the survey object as the default? I don't understand why the survey package behaves the way it does, so changed it. However, this could be really confusing to people who are new to srvyr.

**Comment by ajdamico** [comment]
hi, are you sure that's a reason not to do this?  if you have a list object
holding all parameter defaults, i think you can just access that unless the
user overrides

the f= is one of many params for svyquantile..  i think matching survey
should generally be the default but maybe you have a good argument against
doing so in certain situations.

thanks

**Comment by gergness** [comment]
I'm closing this for now, but I'll consider it when I have more time. I'm not sure I can see what would be gained by adding this ability, and I think it'll cause more problems than you think. 

Beyond just confusion about which function you're passing arguments to (whichever `svy*()` function, `svyby()`, or if you really want to pass a parameter to `confint()`, I think there's a lot of potential for things to break. The `separate` argument to `svyratio()`, totally changes the output in a way that I don't want to have to deal with. Also, for `svyquantile()` passed into a `svyby()`, I need to make sure that `ci = TRUE` because otherwise other things fail.
