### ISSUE TITLE
Ignore missing values via na.rm argument apparently not working for survey_mean()

### ISSUE THREAD

**Issue by j-p-hicks** [gergness/srvyr#149]
Brilliant and very useful package!

I can't seem to get the survey_mean function to ignore missing values though when calculating proportions or grouped means, but it does work for overall means. I've never written more than simple functions so I've got no idea how to help I'm afraid.

Example code below:
```
# Load example dataset and create some missing values

require(srvyr)
require(survey)
data(api, package = "survey")
apistrat$awards[1:3] <- NA
apistrat$api00[1:3] <- NA
dstrata <- apistrat %>%
  as_survey_design(strata = stype, weights = pw) # Create design

# Calculate proportion in each group, but missing appears as a level every time
# depending on whether you use survey_mean or survey_prop with or without
# the na.rm = T argument set and also with or without using the "proportion = T"
# argument for survey_mean.

dstrata %>%
  group_by(awards) %>%
  summarise(pct = survey_prop())

dstrata %>%
  group_by(awards) %>%
  summarise(pct = survey_prop(na.rm = T))

dstrata %>%
  group_by(awards) %>%
  summarise(pct = survey_mean())

dstrata %>%
  group_by(awards) %>%
  summarise(pct = survey_mean(na.rm = T))

dstrata %>%
  group_by(awards) %>%
  summarise(pct = survey_mean(proportion = T))

dstrata %>%
  group_by(awards) %>%
  summarise(pct = survey_mean(na.rm = T))

# Same issue apparently for grouped means

dstrata %>%
  group_by(awards) %>%
  summarise(api00 = survey_mean(api00))

dstrata %>%
  group_by(awards) %>%
  summarise(api00 = survey_mean(api00, na.rm = T))

# But not when not grouping

dstrata %>% summarise(api00 = survey_mean(api00))
dstrata %>% summarise(api00 = survey_mean(api00, na.rm = T))
```

**Comment by bschneidr** [comment]
Hi @j-p-hicks. 

Thanks for sharing the example code, which made it easy to reproduce the issue you were having. To help you communicate on GitHub more effectively in the future, here's a quick introduction to using the "reprex" package to help share both your code and your output. Just wanted to share that since GitHub says this is your first time filing an issue.

https://www.tidyverse.org/help/#reprex-pkg

Anyway, on to your actual issue. Below is a reprex illustrating the behavior you're highlighting.

``` r
suppressMessages({
  suppressWarnings({
    require(srvyr)
    require(survey)
  })
})

# Prepare example design
data(api, package = "survey")
apistrat$awards[1:3] <- NA
apistrat$api00[1:3] <- NA
dstrata <- apistrat %>%
  as_survey_design(strata = stype, weights = pw) # Create design

# Show results of `survey_prop()` where grouping variable has missing data
  dstrata %>%
    group_by(awards) %>%
    summarise(pct = survey_prop())
#> # A tibble: 3 × 3
#>   awards    pct pct_se
#>   <fct>   <dbl>  <dbl>
#> 1 No     0.347  0.0342
#> 2 Yes    0.632  0.0352
#> 3 <NA>   0.0214 0.0122
  
  dstrata %>%
    group_by(awards) %>%
    summarise(pct = survey_prop(na.rm = T))
#> # A tibble: 3 × 3
#>   awards    pct pct_se
#>   <fct>   <dbl>  <dbl>
#> 1 No     0.347  0.0342
#> 2 Yes    0.632  0.0352
#> 3 <NA>   0.0214 0.0122
```

<sup>Created on 2022-12-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

It looks like what you would like the result to be is the summary where records with missing values of the categorical variable have been dropped, as in the following:

``` r
  dstrata %>%
    filter(!is.na(awards)) |>
    group_by(awards) %>%
    summarise(pct = survey_prop())
#> # A tibble: 2 × 3
#>   awards   pct pct_se
#>   <fct>  <dbl>  <dbl>
#> 1 No     0.354 0.0348
#> 2 Yes    0.646 0.0348
```

In general, you can do this using `filter(!is.na(x))` before using `summarise()`. If you have multiple variables you're using, you can use the `if_any()` and `if_all()` functions.

```r
  dstrata %>%
    filter(if_all(c(awards, stype), ~ !is.na(.x))) |>
    group_by(awards, stype) %>%
    summarise(pct = survey_prop())
#> # A tibble: 6 × 4
#> # Groups:   awards [2]
#>   awards stype    pct pct_se
#>   <fct>  <fct>  <dbl>  <dbl>
#> 1 No     E     0.515  0.0484
#> 2 No     H     0.239  0.0290
#> 3 No     M     0.246  0.0342
#> 4 Yes    E     0.813  0.0207
#> 5 Yes    H     0.0617 0.0125
#> 6 Yes    M     0.125  0.0175
```

Given that the desired behavior can be obtained using filtering, I'm not sure that anything needs to be updated with the `na.rm` functionality. So I don't think this is a bug, and the current behavior seems fine to me. But maybe others have thoughts on this.

**Comment by gergness** [comment]
Thanks @bschneidr! (@j-p-hicks - in addition to seconding the recommendation for `reprex`, I also edited your comment to add triple back ticks (\`\`\`) around the code which tells GitHub to display text as code, so that it's more readable).

This has come up a [few times](https://github.com/gergness/srvyr/issues/106), and I see why it's confusing. While I may not make the code work the way it does now if I were writing the code today, I'm not sure there's an alternative that is a clear win, so the recommended solution is what Ben recommended. Sorry for the confusion!

**Comment by j-p-hicks** [comment]
Thanks for the advice on posting. Yes that's fine then if that's the easiest solution. Thanks again for all the hard work on the excellent package.
