### ISSUE TITLE
Convert tbl_svy to data frame

### ISSUE THREAD

**Issue by jamgreen** [gergness/srvyr#19]
Is there a straightforward way output a summzrise call to dataframe?  I am trying to visualize a summarize using ggplot but I cannot coerce my tbl_svy to dataframe. Are there particular rules for outputting to dataframe?

**Comment by ajdamico** [comment]
hi, could you provide a minimal reproducible example of where you are having trouble?  some code from ?tbl_svy

	library(srvyr)
	library(survey)
	library(dplyr)
	data(api)
	svy <- as_survey_design(apistrat, strata = stype, weights = pw)
	
	w <- summarise(svy, col.grad = survey_mean(col.grad),
		  api00 = survey_mean(api00, vartype = "ci"))


	# coerces without issue
	data.frame( w )

**Comment by gergness** [comment]
Yeah - thanks @ajdamico The results from a summarize should be a `tbl_df()` and you can either use them like that (as in other "tidyverse" packages) or you can convert to a data.frame as aj's example shows.

I do see that it might be useful to add a `as.data.frame()` method for `tbl_svy`s, and will try to do so soon. Because srvyr is based on the survey package, In the meantime you could access the underlying data.frame like you can on a survey object:

```r
library(srvyr)
library(survey)
library(dplyr)
data(api)
svy <- as_survey_design(apistrat, strata = stype, weights = pw)

svy$variables
```

**Comment by jamgreen** [comment]
Thank you. That makes sense. I made a mistake on the summarize function. Much appreciated.

-Jamaal
