### ISSUE TITLE
Replicate Weights

### ISSUE THREAD

**Issue by carlganz** [gergness/srvyr#2]
Hello,

This is a pretty neat package, especially since the syntax for the `survey` package feels pretty wonky. This seems like a good direction to go in.

It doesn't appear that this package currently supports replicate weights, but I could be wrong. I've never worked with the `survey` package's source code or `dplyr`'s source code so I'm not sure how difficult it would be to implement replicate weights, but I understand `dplyr` and I'm getting better with C++ and `Rcpp` so perhaps we could work together to build a better survey package.

Regards,
Carl Ganz

**Comment by gergness** [comment]
Hey thanks for your interest! I find it super cool that someone found this.

You're right, replicate weights are not currently supported, but are on my todo list. I think that it should be pretty easy. I'll see if I have any time this weekend to work on it.

I'd love help if you're up for it. I'm looking at this as a learning experience -- I had read Hadley's package development book and wanted to try it out in practice. If you haven't already, I'd recommend reading it, and then feel free to poke around and see what you think should be worked on. So far, the code is really just a wrapper around `survey` and `dplyr`. All the code does is try to work `survey`'s old-school style non-standard evaluation into `lazyeval` objects so that everything can work more like `dplyr`, and then reimplement `dplyr` verbs to work with `survey`'s objects. 

Issue #1 shows my quick first brainstorm on what I want to work on, including the possibility of looking into reimplementing some stuff from `survey` in Rcpp, because I'm kind of worried that `srvyr` is going to be slow. The problem I see is that I can't say I fully understand all of the math behind complex survey design, so I kind of like outsourcing that work to the experts.

**Comment by carlganz** [comment]
Hey,

I will definitely check out Hadley's book when I get a chance. I have a decent understanding of the math behind survey statistics (especially replicate weights since the math is actually pretty simple), and I also have a copy of Professor Lumley's book explaining the `Survey` package, which I highly recommend. 

Truthfully, I probably won't have a lot of time to contribute until next summer, but I think this project has a ton of potential and we could even try applying to the annual [Google Summer of Code](https://www.google-melange.com/gsoc/homepage/google/gsoc2015)

http://en.flossmanuals.net/GSoCStudentGuide/

Regards

**Comment by gergness** [comment]
That'd be really cool if you could pull it off! I do think you'll need to find some group to serve as your mentor besides me -- I don't think I'm qualified, and I'll be busy this summer. Perhaps someone at the original survey package or something like the R consortium, who are supposedly going to start funding projects as well soon, could work.

**Comment by carlganz** [comment]
Sounds good. What I will probably do is spend winter break developing a plan using what you've started here as a jumping off point. In the spring I'll apply, and regardless of any funding I'll dedicate some time next summer to working on it. Of course, you can participate as much or as little as you'd like. 

Regards

**Comment by gergness** [comment]
Awesome, best of luck and keep me posted!

**Comment by gergness** [comment]
Hey, I took a first pass at svrepdesign. Not many of the codepaths are tested yet, so I need to add some more tests, but might be useful for you.

**Comment by carlganz** [comment]
Awesome! I'll take a look this weekend.
