### ISSUE TITLE
Factors in survey_total

### ISSUE THREAD

**Issue by carlganz** [gergness/srvyr#3]
Hey Greg, 
As I find bugs and come up with ideas for things to do I will raise new issues, but obviously none of the issues are urgent.

Here is an issue with factors in survey_total that I've found:

library(srvyr)
library(survey)
data(api)
#create svy object
srs_design<-apisrs %>% design_survey(fpc=fpc)
srs_design
#works correctly
srs_design %>% summarise(totals=survey_total(enroll))
#works correctly
srs_design %>% summarise(means=survey_mean(enroll))
#doesn't work correctly
srs_design %>% summarise(totals=survey_total(stype))

#how it works with the regular survey package
srs_design1<-svydesign(id=~1,fpc=~fpc,data=apisrs)
svytotal(~stype,srs_design1)

Essentially with factors, svytotal gives the weighted frequency for each level of the factor. Same issue with character variables. I will investigate further this weekend.

Regards

**Comment by gergness** [comment]
Good point, I have only tested on numeric variables so far. Presents a bit of a challenge for the api also, because what if you want to summarize by variables with different number of categories. 

My best idea so far is to allow for the inclusion of the factor/character variable in `group_by()` and no variable passed into survey_mean / survey_total would indicate that you want to summarize over groups. 

``` r
library(srvyr)
library(survey)
data(api)
#create svy object
srs_design<-apisrs %>% design_survey(fpc=fpc)

out_survey <- svytotal(~stype, srs_design)

# Doesn't work yet:
out_srvyr <- srs_design %>% 
    group_by(stype) %>% 
    summarise(total = survey_total(), prop = survey_mean())


expect_equal(out_survey[["total"]], unname(out_survey[1:3]))

```

I think this should be just as expressive as survey, if we 'peel' the outermost group.
``` r
svyby(~stype, ~awards, srs_design, svymean)
srs_design %>%
	group_by(awards, stype) %>% # Is this the right order? Need to make sure.
	summarize(mean = survey_mean())

svyby(~awards, ~stype, srs_design, svymean)
srs_design %>%
	group_by(stype, awards) %>%
	summarize(mean = survey_mean())
	
svymean(~paste(stype, awards, sep = "_"), srs_design)
srs_design %>%
	group_by(stype_awards = paste(stype, awards, sep = "_")) %>%
	summarize(mean = survey_mean())
```


If I go this route, need to: 
- add informative error if survey_total or survey_mean receive a factor or character, 
- get survey_total / survey_mean to understand what to do when no variable is passed in, including 'peeling' off a grouping variable

Thanks!

**Comment by gergness** [comment]
Oops didn't close this last week -- should work now, let me know what you think.
