### ISSUE TITLE
Subpopulation analysis

### ISSUE THREAD

**Issue by mlaviolet** [gergness/srvyr#33]
What's the best way to analyze a subpopulation with `srvyr`? My first thought was the `filter` function, but if rows are simply dropped from the data table then the confidence intervals could be incorrect. To obtain correct results the rows should be retained with weights set to zero for rows not belonging to the subpopulation. See Korn and Graubard _Am J Epidemiol_ 1996;144:102-106, or their book _Analysis of Health Surveys_, sec. 5.7. Perhaps a function, say `subpop`, to make this adjustment is needed? Here's an example. Thanks!
```{r}
library(survey)
library(srvyr)
data(api)
dclus1a <-  svydesign(id = ~ dnum, weights = ~ pw, data = apiclus1, fpc = ~ fpc)
dclus1b <- apiclus1 %>% 
  as_survey_design(ids = dnum, weights = pw, fpc = fpc)
t1 <-  svytotal(~ enroll, subset(dclus1a, sch.wide == "Yes" & comp.imp == "Yes"))
t2 <- dclus1b %>% 
  filter(sch.wide == "Yes" & comp.imp == "Yes") %>% 
  summarize(totl = survey_total(enroll, vartype = "ci"))
t1; confint(t1)
t2
# point estimates match; CI's don't
```

**Comment by gergness** [comment]
Hm, interesting. Thanks for reporting with a reproducible example! 

For the main point, why don't your confidence intervals match, the reason is because srvyr automatically provides the degrees of freedom to stats::confint for you, but your call to confint assumes that the degrees of freedom are infinite. For large N, these numbers are approximately the same, but for a small subset like this, they can be quite different:

``` r
suppressPackageStartupMessages({
  library(survey)
  library(srvyr)
})

data(api)
dclus1a <-  svydesign(id = ~ dnum, weights = ~ pw, data = apiclus1, fpc = ~ fpc)

dclus1b <- apiclus1 %>% 
  as_survey_design(ids = dnum, weights = pw, fpc = fpc)


t1 <- svytotal(~ enroll, subset(dclus1a, sch.wide == "Yes" & comp.imp == "Yes"))
confint(t1, df = degf(subset(dclus1a, sch.wide == "Yes" & comp.imp == "Yes")))
#>          2.5 %  97.5 %
#> enroll 1012023 3800816

# Matches srvyr from your original question
dclus1b %>% 
  filter(sch.wide == "Yes" & comp.imp == "Yes") %>% 
  summarize(totl = survey_total(enroll, vartype = "ci"))
#> # A tibble: 1 x 3
#>      totl totl_low totl_upp
#>     <dbl>    <dbl>    <dbl>
#> 1 2406420  1012023  3800816

```
If you prefer to have srvyr work like your original confint call, you can also set the df in `survey_total()`

```r
dclus1b %>% 
  filter(sch.wide == "Yes" & comp.imp == "Yes") %>% 
  summarize(totl = survey_total(enroll, vartype = "ci", df = Inf))
#> # A tibble: 1 x 3
#>      totl totl_low totl_upp
#>     <dbl>    <dbl>    <dbl>
#> 1 2406420  1141373  3671467

# Now srvyr's answer matches your original question's survey results
confint(t1)
#>          2.5 %  97.5 %
#> enroll 1141373 3671467
```


As for your other point about removing the rows instead of setting the weights to zero, you are correct that srvyr does this, but so does the survey package. Here's some code that demonstrates:

``` r
suppressPackageStartupMessages({
  library(survey)
  library(srvyr)
})

data(api)
dclus1a <-  svydesign(id = ~ dnum, weights = ~ pw, data = apiclus1, fpc = ~ fpc)

# Subset number of rows
nrow(subset(dclus1a, sch.wide == "Yes" & comp.imp == "Yes"))
#> [1] 133

# original number of rows
nrow(dclus1a)
#> [1] 183
```

I don't have access to your citations, so can't comment on the correctness of this. Since I'm replicating the behavior of the survey package, I think this issue is best taken up with @tslumley in the survey package.

Thanks!

**Comment by gergness** [comment]
(and sorry for any confusion caused by the different default arguments in `survey_total()`!)

**Comment by tslumley** [comment]
The subset() and [ methods for survey design objects do exactly what they should for subpopulations; they don't just drop the rows. 

For sufficiently simple designs the *implementation* is by dropping the rows and then putting back the all the necessary zeros inside the variance computation.  This can save a lot of memory compared to carrying around all the data.   For designs with calibrated weights the implementation literally just zeroes the weights and doesn't try to save memory.

**Comment by gergness** [comment]
Great, thanks for the explanation @tslumley. Srvyr adapts this code from the survey package, so it will get the same results.
