### ISSUE TITLE
variables created with update() do not work on db-backed designs

### ISSUE THREAD

**Issue by ajdamico** [gergness/srvyr#35]
hi, i'd rather not include srvyr db-backed designs on asdfree till you fix this issue?  i can revert this commit when the fix is on cran, and it'll restore--  https://github.com/ajdamico/asdfree/commit/88ba0dbf95e35e8259c5501d0927e4d2f50fee5f   thanks

	library(dbplyr)
	library(srvyr)
	library(survey)
	library(RSQLite)

	dbclus1<-svydesign(id=~dnum, weights=~pw, fpc=~fpc,
				   data="apiclus1",dbtype="SQLite", dbname=system.file("api.db",package="survey"))

	dbclus1 <- update( dbclus1 , apix = api99 + 1 )

	# added variable works
	svymean(~apix, dbclus1)

	srvyr_design <- as_survey( dbclus1 )

	# works
	srvyr_design %>%
		summarize( mean = survey_mean( api99 , na.rm = TRUE ) )

	# fails	
	srvyr_design %>%
		summarize( mean = survey_mean( apix , na.rm = TRUE ) )

**Comment by gergness** [comment]
Oh, interesting, I didn't think through that use case. I'll have to see if I can find where the survey package is storing the SQL code between `update` and actually pulling the data from the db.

(also need to check on subsets)

Thanks for reporting!

**Comment by gergness** [comment]
I've got limited support working already, but it only works for functions that can be converted to SQL statements by dbplyr. It does work in your example above, but not in all cases. I did make a reasonable warning message for when I can't convert a variable from survey to srvyr.

``` r
suppressPackageStartupMessages({ 
  library(dbplyr)
  library(srvyr)
  library(survey)
  library(RSQLite)
})
# Easy example -----
dbclus1<-svydesign(id=~dnum, weights=~pw, fpc=~fpc,
                   data="apiclus1",dbtype="SQLite", dbname=system.file("api.db",package="survey"))

dbclus1 <- update(  dbclus1 , apix = api99 + 1 )

svymean(~apix, dbclus1)
#>        mean     SE
#> apix 607.98 24.225


# Now works!    
srvyr_design <- as_survey( dbclus1 )
srvyr_design %>%
  summarize( mean = survey_mean( apix , na.rm = TRUE ) )
#> # A tibble: 1 x 2
#>    mean mean_se
#>   <dbl>   <dbl>
#> 1   608    24.2


# Harder example (doesn't work but does have informative warning message) -----
test_function <- function(x) {
  x + 1
}

dbclus1 <- update( dbclus1, apix2 = test_function(api99))
# Weirdly this gives error when using reprex::reprex(), but does work interactively
svymean(~apix2, dbclus1)
#>         mean     SE
#> apix2 607.98 24.225


srvyr_design <- as_survey( dbclus1 )
#> Warning: Could not convert variable 'apix2' from survey database to srvyr database.
#>   Reason: Error in rsqlite_send_query(conn@ptr, statement): no such function: TEST_FUNCTION
```

Looking through asdfree, I found a couple of surveys where I believe that everything will translate properly ([addhealth](https://github.com/ajdamico/asdfree/blob/master/08-addhealth.Rmd)), but a few where not all variables translate. All the problems I've found so far are the `factor` function ([acs](https://github.com/ajdamico/asdfree/blob/master/07-acs.Rmd) is one example).

I'm keeping this open for now and will hopefully take another look soon, but I doubt I'll be able to fix it further. I like my approach of using the db as the place where the calculation happens and suspect that I won't want to adapt it to be more complicated, especially since Professor Lumley seems to at least be investigating using dbplyr for survey's DB integration based on some twitter chatter.

**Comment by gergness** [comment]
Took a closer look, I don't think I'll be able to support arbitrary r functions in srvyr's database, sorry!
