### ISSUE TITLE
ggplot helpers

### ISSUE THREAD

**Issue by gergness** [gergness/srvyr#41]
so you can use geom_smooth (and others?)

Idea from: https://twitter.com/phl43/status/1009007010854076416

**Comment by gergness** [comment]
I think when I wrote this I imagined it being fun to dig into ggplot internals, but I don't actually think this is worth the trouble anymore.

**Comment by bschneidr** [comment]
Thought you might be interested in the following:

https://github.com/juba/questionr/issues/123

It's a pretty slick way of easily incorporating weights from a survey design object into ggplot2. The package author who wrote that acknowledged that it doesn't do variance estimation correctly (for things like error bars or confidence bands), but otherwise this one function is really useful.

https://github.com/larmarange/questionr/blob/dd4a21cd0a6027f9981675e40c56dc1ca375d112/R/ggsurvey.R#L38-L58
