### ISSUE TITLE
feature request: method for `pull`

### ISSUE THREAD

**Issue by dcaseykc** [gergness/srvyr#63]
I'd be nice to have a pull method. My initial thought was to just do it myself and submit a PR, but I can't quite suss out how to do it.

The best I've gotten is:
```
pull.tbl_svy <- function(.data, var = -1){
  pull(.data$variables, var) #dispatches to pull.data.frame if traceback is to be believed
}
```

It works when `var` is a character or numeric, but not when its a symbol (see below). I've tried variations where I `quo`, `enquo`, or `compat_lazy` `var` before passing it on, but to no avail.

```
library('survey')
library('dplyr')
library('srvyr')
data(api)

a = apisrs
b = a %>% as_survey_design(ids = 1, fpc = fpc)

a %>% pull(api00)
b %>% pull(api00) #This will throw an error
```

**Comment by gergness** [comment]
Nice, yea, I agree.

You are close, but I believe you need to use `enquo()` (enquo instead of quo because you're parsing function arguments the user passed in), and then `!!` (bang bang) to tell dplyr to look within the quosure.

So:
```f
pull.tbl_svy <- function(.data, var = -1){
  var <- rlang::enquo(var)
  dplyr::pull(.data$variables, !!var) 
}
```

Do you want to finish in a PR? Would be nice to have a test as well.

**Comment by dcaseykc** [comment]
Huh. I swear I tried enquo during my shotgun debugging approach. Ah well. PR #64 addresses things (I think).

Thanks!
