### ISSUE TITLE
Inconsistent behavior with unweighted()

### ISSUE THREAD

**Issue by tlmcmurry** [gergness/srvyr#70]
Thank you for your work on this package!  I could see it being super helpful.  I've been testing this package to make tables of descriptive statistics and ran into some odd behavior with unweighted().  In a grouped analysis, if unweighted is called directly from summarize, you get the correct answer.  If you put unweighted() in a wrapper function, you don't.  This is in contrast to survey_mean and survey_quantile, which seem to behave correctly.

Here's an example:

```r
library(srvyr)

# Make some toy data
data <- data.frame(group = rep(c("A", "B"), each = 3),
	sex = rep(c(0, 1), times = 3),
	strata = 1,
	weight = 1)

# Make it a survey
data_svy <- as_survey(data, strata = strata, weight = weight)

# Try unweighted(), works great
group_by(data_svy, group) %>%
	summarize(sex_1_pct = unweighted(100*mean(sex)))

# Wrapper function
unweighted_mean <- function(x) {
	data.frame(unweighted(100*mean(x)))
}

# Using wrapper function returns wrong answer
group_by(data_svy, group) %>%
	summarize(unweighted_mean(sex))
```

**Comment by gergness** [comment]
Hi, thanks for the report and the great reprex! 

The non-standard evaluation semantics of dplyr and srvyr get in the way here. Your code should produce an error and does in the commit I just pushed.

```r
group_by(data_svy, group) %>%
	summarize(unweighted_mean(sex))

#>  Error in mean(x) : object 'x' not found 
```

To do this correctly your function needs to interpolate the argument so that it evaluates in the right context. The currently recommended way to do that is with the ["curly curly" operator](https://www.tidyverse.org/blog/2019/06/rlang-0-4-0/) like so:

```r
library(srvyr)

# Make some toy data
data <- data.frame(group = rep(c("A", "B"), each = 3),
	sex = rep(c(0, 1), times = 3),
	strata = 1,
	weight = 1)

# Make it a survey
data_svy <- as_survey(data, strata = strata, weight = weight)

unweighted_mean <- function(x) {
	unweighted(100*mean({{x}}) # note the {{ around x here
}

# Using wrapper function returns wrong answer
group_by(data_svy, group) %>%
	summarize(unweighted_mean(sex))
```

I've updated so that there's an error and tried to [update documentation to explain](https://github.com/gergness/srvyr/blob/c40f070d4589f448e0b4eb2299148246769e3eea/R/survey_statistics.r#L679), but would love any feedback you have on how this, because it's a tough topic to teach!
