### ISSUE TITLE
srvyr won't work with dplyr 0.8.99.9002

### ISSUE THREAD

**Issue by pachamaltese** [gergness/srvyr#73]
please see the problem reported here:
https://github.com/pachamaltese/casen/issues/9#issuecomment-610743932

**Comment by gergness** [comment]
Hi, thank you for reporting. I was informed by the dplyr maintainers, and had some time to work on it this past weekend, but didn't commit and push my work. I now have, so you can get that from `devtools::install_github("gergness/srvyr")`

There are still some failing tests (at least one is because of a downstream package to me), so I still have some work to do. However, if you want, you can check if I've fixed the issue you were seeing.

**Comment by pachamaltese** [comment]
thanks a lot
how can I help?
