### ISSUE TITLE
ordered factors beak when unpeeled in survey_count

### ISSUE THREAD

**Issue by gergness** [gergness/srvyr#91]
https://github.com/walkerke/tidycensus/pull/274#issuecomment-662991817

@bschneidr - seems closely related to #88, any chance you can take a look?

```r
library(tidyverse)
library(survey)
library(srvyr)


data(api)

apisrs_mut <- apisrs %>%
  as_tibble() %>%
  mutate(stype_factor=parse_factor(as.character(stype), levels=c("E", "M", "H")),
         stype_ordered_factor=parse_factor(as.character(stype), levels=c("E", "M", "H"), ordered = TRUE))

apisrs_mut %>% select(starts_with("stype")) %>% summary()
#>  stype   stype_factor stype_ordered_factor
#>  E:142   E:142        E:142               
#>  H: 25   M: 33        M: 33               
#>  M: 33   H: 25        H: 25

srs_design_srvyr  <- apisrs_mut %>%
  as_survey_design(ids = 1, fpc = fpc)

srs_design_srvyr %>%
  survey_count(stype_ordered_factor)

#> Error: Can't join on `x$stype_ordered_factor` x `y$stype_ordered_factor` because of incompatible types.
#> i `x$stype_ordered_factor` is of type <ordered<90f33>>>.
#> i `y$stype_ordered_factor` is of type <factor<90f33>>>.
```

**Comment by bschneidr** [comment]
Absolutely. This does seem like it must be related to #88.

**Comment by bschneidr** [comment]
I've added a pull request which I think should fix the issue, but here is the explanation for the bug.

The root cause is that the following functions don't distinguish between ordered and unordered factors:

- `factor_stat_reshape()`
- `get_var_est_factor()`

As a result, the output of `survey_stat_factor()` has a column which is an unordered factor, despite the fact that the corresponding input column was an ordered factor. This causes trouble when `survey_stat_factor()` is used inside `summarise.grouped_svy`, where it causes the `calculations` object created in the function to end up with a column named `stype_ordered_factor` which is only an unordered factor.

https://github.com/gergness/srvyr/blob/6c379d9960307fe786bcdeef6ccf5828191d25fe/R/summarise.r#L51-L65

which ultimately results `semi_join()` trying to join on the basis of an unordered factor and an ordered factor, which {dplyr} does not allow. 
https://github.com/gergness/srvyr/blob/6c379d9960307fe786bcdeef6ccf5828191d25fe/R/summarise.r#L92
