### ISSUE TITLE
svyquantile changes

### ISSUE THREAD

**Issue by gergness** [gergness/srvyr#94]
Plan is to use `oldsvyquantile` when available for now, but should replace it after survey update is released

> There's a new version 4.1 of the survey package that will be coming soon.  It includes a complete rewrite of svyquantile(), which is likely to break the quantile code in srvyr.
> 
> The quick solution is to call oldsvyquantile(), which is the new name for the current function, there for backwards compatibility.  In the longer term, though, I think the new svyquantile() function is better organised, and has a more sensible selection of ways to define the quantile. 
> 
> A version of the package that passes CMD check is here: http://r-forge.r-project.org/R/?group_id=1788

**Comment by gergness** [comment]
step 1 in https://github.com/gergness/srvyr/commit/298047521c4ca489a03d05f81a3ba5aee2a70e2d

**Comment by bschneidr** [comment]
I've started updating the functions and tests here and am hoping to submit a pull request by Friday. I think the function updates are actually going to be pretty easy, but there are a lot of tests to update since the format of the {survey} output has changed with the new quantile function.
https://github.com/bschneidr/srvyr/tree/use-new-svyquantile
I'm curious whether you think it's worth supporting the `oldsvyquantile()` going forward, either with a new function `survey_oldquantile()` or with some additional arguments to `survey_quantile()`/`survey_median()`. I would guess it's probably not worth the trouble. For one thing, I can't imagine too many users of `survey` really used settings other than the default. For another, the {survey} package I think makes it harder than strictly necessary to use the old quantile functionality.

**Comment by gergness** [comment]
Hm, there are a lot of issues filed from people trying to replicate numbers exactly (usually between `survey` and `srvyr`, but I can imagine it messing people up between versions). I think I'd prefer  an `survey_oldquantile()` if it's not too much work. Testing can be limited, and probably should only emit a warning if it fails (no error) to try to give more freedom to the survey package to remove it.

**Comment by gergness** [comment]
(And thank you so much!)

**Comment by gergness** [comment]
closed in #124
